# Generated by Django 5.2.1 on 2025-05-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_categoria_produto_categoria_itemcarrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
