# Generated by Django 5.2.1 on 2025-05-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
