# Generated by Django 5.2.1 on 2025-05-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
